---
title: "DAWG_matrix_algebra"
author: "Redgar"
date: "February 22, 2017"
output: html_document
---
# Matrix Algebra
```{r setup, include=FALSE, echo=FALSE}
library(rafalib)
library(UsingR)
```

### Motivatin' examples

#### Parabola
```{r}
set.seed(1)
g <- 9.8 ##meters per second
n <- 25
tt <- seq(0,3.4,len=n) ##time in secs, note: we use tt because t is a base function
d <- 56.67  - 0.5*g*tt^2 + rnorm(n,sd=1) ##meters
mypar()
plot(tt,d,ylab="Distance in meters",xlab="Time in seconds")
```

####  Linear
```{r}
x=father.son$fheight
y=father.son$sheight
plot(x,y,xlab="Father's height",ylab="Son's height")
```


####  Grouped (t-test)
```{r}
dat <- read.csv("femaleMiceWeights.csv")
mypar(1,1)
stripchart(Bodyweight~Diet,data=dat,vertical=TRUE,method="jitter",pch=1,main="Mice weights")
```

#### Residuals 
```{r}
g <- 9.8 ##meters per second
n <- 25
tt <- seq(0,3.4,len=n) ##time in secs, t is a base function
f <- 56.67 - 0.5*g*tt^2
y <- f + rnorm(n,sd=1)
plot(tt,y,ylab="Distance in meters",xlab="Time in seconds")
lines(tt,f,col=2)
```


#### lm function
```{r}
# Esitmate is the least squares estimate (LSE)
tt2 <-tt^2
fit <- lm(y~tt+tt2)
summary(fit)$coef
```

#### Explain math behind lm
```{r}
rss <- function(Beta0,Beta1,Beta2){
  r <- y - (Beta0+Beta1*tt+Beta2*tt^2)
  return(sum(r^2))
}

Beta2s<- seq(-10,0,len=100)
plot(Beta2s,sapply(Beta2s,rss,Beta0=55,Beta1=0),
     ylab="RSS",xlab="Beta2",type="l")
##Let's add another curve fixing another pair:
Beta2s<- seq(-10,0,len=100)
lines(Beta2s,sapply(Beta2s,rss,Beta0=65,Beta1=0),col=2)
```

## Excercise
```{r}
data("father.son",package="UsingR")
#1
mean(father.son$sheight)
#2
father.son$fhright_round<-round(father.son$fheight)
mean(father.son$sheight[which(father.son$fhright_round==71)])
#3 C
#4 A
```

### Matrix Notation

```{r}
data(father.son,package="UsingR")
y=father.son$fheight
head(y)

n <- 25
tt <- seq(0,3.4,len=n) ##time in secs, t is a base function
X <- cbind(X1=tt,X2=tt^2)
head(X)
dim(X)

N <- 100; p <- 5
X <- matrix(1:(N*p),N,p)
head(X)

N <- 100; p <- 5
X <- matrix(1:(N*p),N,p,byrow=TRUE)
head(X)
```


## Excercise 2
```{r}
#1
c(1,5,3,4)
rnorm(10)
X = matrix(1:1000,100,10)
X[25,3]

#2
x<-1:10
X <- cbind(x,2*x,3*x,4*x,5*x)
sum(X[7,])

#3 B
```

## Multiplying by a scalar
```{r}
X <- matrix(1:12,4,3)
print(X)
a <- 2
print(a*X)

X <- matrix(1:12,4,3)
X

t(X)
```

#Matrix multiplication
```{r}
X <- matrix(c(1,3,2,1,-2,1,1,1,-1),3,3)
abc <- c(3,2,1) #use as an example
rbind( sum(X[1,]*abc), sum(X[2,]*abc), sum(X[3,]%*%abc))

X%*%abc
```


## Excercise 3
```{r}
#1 B
#2 
X <- matrix(c(3,2,1,5, 4,2,-1,0, -5,2,5,0, 1,-1,-5,1),4,4)
y <- matrix(c(10,5,7,4),4,1)
solve(X)%*%y #c=-0.8849558
      #check
      abcd<-solve(X)%*%y
      X%*%abcd
#3
a <- matrix(1:12, nrow=4)
b <- matrix(1:15, nrow=3)
X<-a%*%b
X[3,2] 

#4
sum(a[3,]*b[,2])

```


# Examples
```{r}
library(UsingR)
y <- father.son$sheight
print(mean(y))

# mean from matrices
N <- length(y)
Y<- matrix(y,N,1)
A <- matrix(1,N,1)
barY=t(A)%*%Y / N

print(barY)
barY=crossprod(A,Y) / N
print(barY)

#Variance
# values - mean
r <- y - barY
crossprod(r)/N

library(rafalib)
popvar(y)

## LSE in R
library(UsingR)
x=father.son$fheight
y=father.son$sheight
X <- cbind(1,x)
betahat <- solve( t(X) %*% X ) %*% t(X) %*% y
###or
betahat <- solve( crossprod(X) ) %*% crossprod( X, y )


set.seed(1)
g <- 9.8 #meters per second
n <- 25
tt <- seq(0,3.4,len=n) #time in secs, t is a base function
d <- 56.67 - 0.5*g*tt^2 + rnorm(n,sd=1)
X <- cbind(1,tt,tt^2)
y <- d
betahat <- solve(crossprod(X))%*%crossprod(X,y)
newtt <- seq(min(tt),max(tt),len=100)
X <- cbind(1,newtt,newtt^2)
fitted <- X%*%betahat
plot(tt,y,xlab="Time",ylab="Height")
lines(newtt,fitted,col=2)
```

# Excercises
```{r}
#1 5
X <- matrix(c(1,1,1,1,0,0,1,1),nrow=4)
rownames(X) <- c("a","a","b","b")
X

beta <- c(5, 2)
fitted <- X%*%beta
# 2 7
# 3

X <- matrix(c(1,1,1,1,1,1,0,0,1,1,0,0,0,0,0,0,1,1),nrow=6)
rownames(X) <- c("a","a","b","b","c","c")
X
beta <- c(10,3,-3)
fitted <- X%*%beta

```


