---
title: "Meeting_March28"
author: "Rachel Edgar"
date: "March 25, 2017"
output: html_document
---

```{r}
library(rafalib)
library(UsingR)
```


# Excercise 1
```{r}
g = 9.8
h0 = 56.67
v0 = 0
n = 25
tt = seq(0,3.4,len=n)
y = h0 + v0 *tt - 0.5* g*tt^2 + rnorm(n,sd=1)

X = cbind(1,tt,tt^2)
A = solve(crossprod(X))%*%t(X)

# 1 C
-2 * (A %*% y) [3]

# 2
se<-function(x) sd(x)/sqrt(length(x))

est_g<-function(x) {
  y = h0 + v0 *tt - 0.5* g*tt^2 + rnorm(n,sd=1)
  X = cbind(1,tt,tt^2)
  A = solve(crossprod(X))%*%t(X)
  -2 * (A %*% y) [3]
}

g_estimates<-replicate(100000,est_g(1), simplify = "array")
se(g_estimates)

# 3

x = father.son$fheight
y = father.son$sheight
n = length(y)

N = 50
index = sample(n,N)
sampledat = father.son[index,]
x = sampledat$fheight
y = sampledat$sheight
betahat = lm(y~x)$coef
slope = lm(y~x)$coef[2]
slope

slope_height<-function(x){
  N = 50
  index = sample(n,N)
  sampledat = father.son[index,]
  x = sampledat$fheight
  y = sampledat$sheight
  betahat = lm(y~x)$coef
  slope = lm(y~x)$coef[2]
  slope
}


slope_estimates<-replicate(10000,slope_height(1), simplify = "array")
se(slope_estimates)

# 4 C

x = father.son$fheight
y = father.son$sheight

mean((y - mean(y))*(x-mean(x)))
```

# The design matrix
```{r}
group <- factor( c(1,1,2,2) )
model.matrix(~ group)

diet <- factor(c(1,1,1,1,2,2,2,2))
sex <- factor(c("f","f","m","m","f","f","m","m"))
model.matrix(~ diet + sex)
```

