---
title: "Data Pre-processing"
author: "Rachel Edgar"
date: '2015-11-22'
output: pdf_document
---

Load Libraries

--------------------------------------------------------------------------------

```{r}
library(ggplot2)
library(reshape)
```


Read in the data
--------------------------------------------------------------------------------

```{r}
load("~/Documents/Presentations/graspods_workshop/graspods_redgar_GSE59685_minimal_data.RData")
```


Common Genomics Data Format
--------------------------------------------------------------------------------

```{r}
Betas[1:5,1:5]
head(Meta)
```

Quality Control (QC)
--------------------------------------------------------------------------------

```{r}
## NA Count in samples
na_count_sample <-sapply(Betas, function(y) sum(length(which(is.na(y)))))
na_count_sample

## NA Count in probes
na_count_probe <-sapply(1:nrow(Betas), function(y) length(which(is.na(Betas[y,]))))
Betas[na_count_probe>0,]

## filter to probes with no NAs (stringent threshold should be more relaxed in a full dataset)
Betas_clean<-Betas[na_count_probe==0,]
```

## Cluster by sex chromosomes
```{r}
# filter to probes on X and Y
# note we are using Betas_clean here

sex<-Annotation[which(Annotation$CHR%in%c("Y","X")),]
sex_beta<-Betas_clean[which(rownames(Betas_clean)%in%sex$ILMNID),]
sex_beta<-sex_beta[complete.cases(sex_beta),]

#cluster and plot
sex_clust <- hclust(dist(t(sex_beta)))
plot(sex_clust)

## Add fancy labels
plot(sex_clust, labels=Meta$Sex) 
```

## Distributions of data are a useful general QC tool

```{r}
## melt is a crazy magic R function that reshapes data 
Beta_Plot<- melt(Betas_clean)
#add meta data
Beta_Plot<-merge(Beta_Plot,Meta, by.x="variable", by.y="gsm")
head(Beta_Plot)

ggplot(Beta_Plot, aes(value, group=variable, color=Tissue))+geom_density()+theme_bw()
```

# Sample correlation heat maps can show outliers
```{r}
qplot(x=X1, y=X2, data=melt(cor(Betas_clean)), fill=value, geom="tile")
```

Normalization
--------------------------------------------------------------------------------
The types are specific and the packages are large. So we won't do it today. See the slides notes for a starting place on researching the best normalization for your data. 

Principal Components Analysis
--------------------------------------------------------------------------------

```{r}
PCA_full<-princomp(Betas_clean)
Loadings<-as.data.frame(unclass(PCA_full$loadings))

Loadings[1:5,1:5]

# Correlate PC1 and age of the sample
cor(Loadings[,1],as.numeric(Meta$age.blood))
# ANOVA PC1 and Tissue of the sample
summary(aov(Loadings[,1]~Meta$Tissue))

# ANOVA PC2 and Tissue of the sample
summary(aov(Loadings[,2]~Meta$Tissue))
# ANOVA PC2 and sex of the sample
summary(aov(Loadings[,2]~Meta$Sex))

# its weird probably because it is a tiny dataset...
ggplot(Loadings,aes(Comp.1,Comp.2, fill=Meta$Tissue))+geom_point(shape=21, color="black", size=3)+theme_bw()
```
